export enum Theme {
  BLANK = "BLANK",
  BALOONS = "BALOONS",
  // DDD_TEXT = "DDD_TEXT",
  // EMOJI_RAIN = "EMOJI_RAIN",
  // GLITCH_TEXT = "GLITCH_TEXT",
  // HOUR_GLASS = "HOUR_GLASS",
  // MATRIX = "MATRIX",
  // NEON = "NEON",
  // SLIDING_TEXT = "SLIDING_TEXT",
  // CHRISTMAS = "CHRISTMAS",
}
